vich_uploader:
    db_driver: orm

    mappings:
        courses:
            uri_prefix: /uploads/documents/
            upload_destination: '%kernel.project_dir%/public/uploads/documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # permet d'avoir des noms de fichier unique
